### ISSUE TITLE
Python3.11 with Django

### ISSUE THREAD

**Issue by SGabor111** [theriverman/szamlazz.py#1]
Hi,

Thank you for writing this great script, works perfect on 3.10 Python with Django.

I was trying to upgrade to 3.11 but it seems that lxml the dependencie is not good when upgrading. Can you change the requirements files so it can work with python 3.11.
Thanks

**Comment by theriverman** [comment]
Hi @SGabor111 ,

Thanks for reporting this issue with Python 3.11 and lxml. I have updated the required dependencies to their latest and the installation now works fine on my machine under 3.11. In parallel to these changes, support for Python 3.6 has been dropped.

Please let me know if it works for you too!

**Comment by SGabor111** [comment]
Thanks works great!
