### ISSUE TITLE
Change http to https in client.py

### ISSUE THREAD

**Issue by ebingerdavid** [theriverman/szamlazz.py#2]
Hi, 

First thank you for your work:) 
I just recognized some "http" hard coding URL in client.py
It would be great if you could fix it in the feature.

David

**Comment by theriverman** [comment]
Hi @ebingerdavid,

Could you elaborate and point me to these hardcoded http instances, please?
If you mean the default (not hardcoded) values for `xml_namespace` then it's not a mistake. See https://docs.szamlazz.hu/#example-xml for more.
