### ISSUE TITLE
tax_number_eu is not render for invoice. 

### ISSUE THREAD

**Issue by awintersk** [theriverman/szamlazz.py#4]
please add line 
        <adoszamEU>{{ buyer.tax_number_eu }}</adoszamEU>
into template.py to be possible to send EU VAT number to szamlazz.

**Comment by theriverman** [comment]
@awintersk 
it's already present in line 112:
https://github.com/theriverman/szamlazz.py/blob/17e4cfda767a1ef158bb9ff0f952e3998a9dc2d8/szamlazz/templates.py#L109-L113

Could you give me more elaborate instructions on what are you actually missing from the template? What would be the tag? Is it `<adoszamEU>` as well?

**Comment by awintersk** [comment]
Hi Kristof

 �

The line that you send me is aplied only for reverse invoice.  ( if i �understand hu invoicing correctly )

 �

In case i �am sending regulat invoice the vevo element contains only

<vevo>

        <nev>{{ buyer.name }}</nev>

        <irsz>{{ buyer.zip_code }}</irsz>

        <telepules>{{ buyer.city }}</telepules>

        <cim>{{ buyer.address }}</cim>

        <email>{{ buyer.email }}</email>

        <sendEmail>{{ buyer.send_email | lower }}</sendEmail>

        <adoszam>{{ buyer.tax_number }}</adoszam>

        <postazasiNev>{{ buyer.delivery_name }}</postazasiNev>

        <postazasiIrsz>{{ buyer.delivery_zip }}</postazasiIrsz>

        <postazasiTelepules>{{ buyer.delivery_city }}</postazasiTelepules>

        <postazasiCim>{{ buyer.delivery_address }}</postazasiCim>

        <azonosito>{{ buyer.identification }}</azonosito>

        <telefonszam>{{ buyer.phone_number }}</telefonszam>

        <megjegyzes>{{ buyer.comment }}</megjegyzes>

    </vevo>

 �

On the invoice is than not shown Customer VAT number also in case  buyer.tax_number_eu is filled.

 �

Thats the reason why i �need to add it into line 52.

<vevo>
    <nev>{{ buyer.name }}</nev>
    <irsz>{{ buyer.zip_code }}</irsz>
    <telepules>{{ buyer.city }}</telepules>
    <cim>{{ buyer.address }}</cim>
    <email>{{ buyer.email }}</email>
    <sendEmail>{{ buyer.send_email | lower }}</sendEmail>
    <adoszam>{{ buyer.tax_number }}</adoszam>
    <adoszamEU>{{ buyer.tax_number_eu }}</adoszamEU>
    <postazasiNev>{{ buyer.delivery_name }}</postazasiNev>
    <postazasiIrsz>{{ buyer.delivery_zip }}</postazasiIrsz>
    <postazasiTelepules>{{ buyer.delivery_city }}</postazasiTelepules>
    <postazasiCim>{{ buyer.delivery_address }}</postazasiCim>
    <azonosito>{{ buyer.identification }}</azonosito>
    <telefonszam>{{ buyer.phone_number }}</telefonszam>
    <megjegyzes>{{ buyer.comment }}</megjegyzes>
</vevo>

 �

After this change I �am able to send VAT number to Samlazz and will be shown on invoice.

 �

Thank you

Andrej

 �

**Comment by theriverman** [comment]
@awintersk I see what's missing now. I have created both the models and the templates based on the XML examples provided in the documentation and I didn't sync them up with the XSD scheme.
Please pull `szamlazz.py==1.3.0rc1` (https://pypi.org/project/szamlazz.py/1.3.0rc1/) and see if it does what you expect. Once you confirm it's working, I'll release 1.3.0 properly.
Thanks!

**Comment by awintersk** [comment]
Hi 

  

After tests i  wil let you know.

  

Thank you

andrej

**Comment by awintersk** [comment]
Hi 

  

I  have got error

szamlazz.xsd.ValidationError: XML validation failed: <string>:54:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://www.szamlazz.hu/xmlszamla}csoportazonosito': This element is not expected. Expected is one of ( {http://www.szamlazz.hu/xmlszamla}adoszamEU, {http://www.szamlazz.hu/xmlszamla}postazasiNev, {http://www.szamlazz.hu/xmlszamla}postazasiOrszag, {http://www.szamlazz.hu/xmlszamla}postazasiIrsz, {http://www.szamlazz.hu/xmlszamla}postazasiTelepules, {http://www.szamlazz.hu/xmlszamla}postazasiCim, {http://www.szamlazz.hu/xmlszamla}vevoFokonyv, {http://www.szamlazz.hu/xmlszamla}azonosito, {http://www.szamlazz.hu/xmlszamla}alairoNeve, {http://www.szamlazz.hu/xmlszamla}telefonszam ).

  

Is there an erro of our implemetation? We do not use csoportazonosito (  <csoportazonosito>{{ buyer.group_id }}</csoportazonosito>)

This line has been added from my previous version (1.1.0).

 �

Thank you

Andrej

  

From: ***@***.*** ***@***.***> 
Sent: Monday, January 29, 2024 7:41 AM
To: 'theriverman/szamlazz.py' ***@***.***>; 'theriverman/szamlazz.py' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [theriverman/szamlazz.py] tax_number_eu is not render for invoice. (Issue #4)

 �

Hi 

  

After tests i  wil let you know.

  

Thank you

andrej

**Comment by awintersk** [comment]
Hi

  

I  did test it. There is issue with xsd.py file, values are missing in xsd schema. I  did added it there and basic test passed.

  

Could you be please so kind and fix it soon, that I  will be able to add it into test environment?

  

Thank you

Andrej

  

From: ***@***.*** ***@***.***> 
Sent: Monday, January 29, 2024 8:17 AM
To: 'theriverman/szamlazz.py' ***@***.***>; 'theriverman/szamlazz.py' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [theriverman/szamlazz.py] tax_number_eu is not render for invoice. (Issue #4)

 �

Hi 

  

I  have got error

szamlazz.xsd.ValidationError: XML validation failed: <string>:54:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://www.szamlazz.hu/xmlszamla}csoportazonosito': This element is not expected. Expected is one of ( {http://www.szamlazz.hu/xmlszamla}adoszamEU, {http://www.szamlazz.hu/xmlszamla}postazasiNev, {http://www.szamlazz.hu/xmlszamla}postazasiOrszag, {http://www.szamlazz.hu/xmlszamla}postazasiIrsz, {http://www.szamlazz.hu/xmlszamla}postazasiTelepules, {http://www.szamlazz.hu/xmlszamla}postazasiCim, {http://www.szamlazz.hu/xmlszamla}vevoFokonyv, {http://www.szamlazz.hu/xmlszamla}azonosito, {http://www.szamlazz.hu/xmlszamla}alairoNeve, {http://www.szamlazz.hu/xmlszamla}telefonszam ).

  

Is there an erro of our implemetation? We do not use csoportazonosito (  �<csoportazonosito>{{ buyer.group_id }}</csoportazonosito>)

This line has been added from my previous version (1.1.0).

 �

Thank you

Andrej

  

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: Monday, January 29, 2024 7:41 AM
To: 'theriverman/szamlazz.py' ***@***.*** ***@***.***> >; 'theriverman/szamlazz.py' ***@***.*** ***@***.***> >
Cc: 'Mention' ***@***.*** ***@***.***> >
Subject: RE: [theriverman/szamlazz.py] tax_number_eu is not render for invoice. (Issue #4)

 �

Hi 

  

After tests i  wil let you know.

  

Thank you

andrej

**Comment by awintersk** [comment]
HI Kristof

 �

Did you reeived my mails?

 �

Please write me answer, it is little bit urgent. The xsd.py file missing 3 parameters in invoice scheme to be vorking.

If its faster please give me your phone number – i �will call you back.

 �

Thank you

Andrej 

 �

From: ***@***.*** ***@***.***> 
Sent: Monday, January 29, 2024 9:49 AM
To: 'theriverman/szamlazz.py' ***@***.***>; 'theriverman/szamlazz.py' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [theriverman/szamlazz.py] tax_number_eu is not render for invoice. (Issue #4)

 �

Hi

 �

I �did test it. There is issue with xsd.py file, values are missing in xsd schema. I �did added it there and basic test passed.

 �

Could you be please so kind and fix it soon, that I �will be able to add it into test environment?

 �

Thank you

Andrej

 �

From:  ***@***.***> ***@***.*** < ***@***.***> ***@***.***> 
Sent: Monday, January 29, 2024 8:17 AM
To: 'theriverman/szamlazz.py' < ***@***.***> ***@***.***>; 'theriverman/szamlazz.py' < ***@***.***> ***@***.***>
Cc: 'Mention' < ***@***.***> ***@***.***>
Subject: RE: [theriverman/szamlazz.py] tax_number_eu is not render for invoice. (Issue #4)

 �

Hi 

 �

I �have got error

szamlazz.xsd.ValidationError: XML validation failed: <string>:54:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://www.szamlazz.hu/xmlszamla}csoportazonosito': This element is not expected. Expected is one of ( {http://www.szamlazz.hu/xmlszamla}adoszamEU, {http://www.szamlazz.hu/xmlszamla}postazasiNev, {http://www.szamlazz.hu/xmlszamla}postazasiOrszag, {http://www.szamlazz.hu/xmlszamla}postazasiIrsz, {http://www.szamlazz.hu/xmlszamla}postazasiTelepules, {http://www.szamlazz.hu/xmlszamla}postazasiCim, {http://www.szamlazz.hu/xmlszamla}vevoFokonyv, {http://www.szamlazz.hu/xmlszamla}azonosito, {http://www.szamlazz.hu/xmlszamla}alairoNeve, {http://www.szamlazz.hu/xmlszamla}telefonszam ).

 �

Is there an erro of our implemetation? We do not use csoportazonosito (  �<csoportazonosito>{{ buyer.group_id }}</csoportazonosito>)

This line has been added from my previous version (1.1.0).

 �

Thank you

Andrej

 �

From:  ***@***.***> ***@***.*** < ***@***.***> ***@***.***> 
Sent: Monday, January 29, 2024 7:41 AM
To: 'theriverman/szamlazz.py' < ***@***.***> ***@***.***>; 'theriverman/szamlazz.py' < ***@***.***> ***@***.***>
Cc: 'Mention' < ***@***.***> ***@***.***>
Subject: RE: [theriverman/szamlazz.py] tax_number_eu is not render for invoice. (Issue #4)

 �

Hi 

 �

After tests i �wil let you know.

 �

Thank you

andrej

 �

 �

**Comment by theriverman** [comment]
Hi @awintersk 
Sorry, I can only pay attention to this project on the weekends.

Please pull `szamlazz.py==1.3.0rc2` (https://pypi.org/project/szamlazz.py/1.3.0rc2/) and see if it does what you expect.
Thanks
