### ISSUE TITLE
Potential TypeError in SzamlazzResponse.__init___()

### ISSUE THREAD

**Issue by volfpeter** [theriverman/szamlazz.py#6]
The `if "application/octet-stream" in content_type:` check will fail with `TypeError` if the `Content-Type` header is missing. See my comment and the original implementation in #5

**Comment by theriverman** [comment]
See my https://github.com/theriverman/szamlazz.py/pull/5#discussion_r1583838018.

**Comment by volfpeter** [comment]
See my response in the merge request thread.

**Comment by theriverman** [comment]
Finally solved in commit [2a29d16](https://github.com/theriverman/szamlazz.py/commit/2a29d16d949579d6fe355a03701f5b85641cde54)
